### ISSUE TITLE
Question Regarding the yolov4 tiny model being used 

### ISSUE THREAD

**Issue by sathwick-p** [MirCore/Unity-Object-Detection-and-Localization-with-VR#3]
Hey, i'd like to know whether the object detection model which has been implemented in this project can detect only person, chair and bottle or can it detect other objects too?

If so can you please guide me on how to implement other objects too?
Thank you.

**Comment by MirCore** [comment]
Hi, the YOLOv4 model used in this project can recognise these objects:

`"Plane", "Bicycle", "Bird", "Boat", "Bottle", "Bus", "Car", "Cat", "Chair", "Cow", "Table", "Dog", "Horse", "Motorbike", "Person", "Plant", "Sheep", "Sofa", "Train", "TV"'.

The model can be replaced, but I never looked into how that works. See Keijiro's [YoloV4TinyBarracuda](https://github.com/keijiro/YoloV4TinyBarracuda) for more information on the YOLO implementation.
